version: '3'
services:
  db:
    image: 'postgres:12.18'
    environment:
      POSTGRES_DB: ${APP_DB_NAME}
      POSTGRES_PASSWORD: ${APP_DB_PASS}
      POSTGRES_USER: ${APP_DB_USERNAME}
    ports:
      - '5432:5432'
  application:
    image: backend-engineer-assessment:1.0.0
    environment:
      APP_DB_URL: ${APP_DB_URL}
      APP_DB_USERNAME: ${APP_DB_USERNAME}
      APP_DB_PASSWORD: ${APP_DB_PASS}
      APP_SHOW_SQL: ${APP_SHOW_SQL}
      APP_DB_MIN_IDLE: ${APP_DB_MIN_IDLE}
      APP_DB_POOL_SIZE: ${APP_DB_POOL_SIZE}
      APP_DB_IDLE_TIMEOUT: ${APP_DB_IDLE_TIMEOUT}
      APP_DB_MAX_LIFETIME: ${APP_DB_MAX_LIFETIME}
      APP_DB_CONNECTION_TIMEOUT: ${APP_DB_CONNECTION_TIMEOUT}
      STRIPES_API_KEY: ${STRIPES_API_KEY}
      TEMPORAL_API_URL: ${TEMPORAL_API_URL}
      APP_LOGGING_LEVEL_ROOT: ${APP_LOGGING_LEVEL_ROOT}
      APP_LOGGING_LEVEL_SQL: ${APP_LOGGING_LEVEL_SQL}
      APP_LOGGING_LEVEL_WEB: ${APP_LOGGING_LEVEL_WEB}
      APP_LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: ${APP_LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB}
      APP_TEMPORAL_CONNECTION_WORKFLOW_TASK_TIMEOUT: ${APP_TEMPORAL_CONNECTION_WORKFLOW_TASK_TIMEOUT}
      APP_TEMPORAL_CONNECTION_WORKFLOW_EXECUTION_TIMEOUT: ${APP_TEMPORAL_CONNECTION_WORKFLOW_EXECUTION_TIMEOUT}
      APP_TEMPORAL_CONNECTION_WORKFLOW_RUN_TIMEOUT: ${APP_TEMPORAL_CONNECTION_WORKFLOW_RUN_TIMEOUT}
      APP_TEMPORAL_CONNECTION_ACTIVITY_START_TO_CLOSE_TIMEOUT: ${APP_TEMPORAL_CONNECTION_ACTIVITY_START_TO_CLOSE_TIMEOUT}
      APP_TEMPORAL_CONNECTION_ACTIVITY_SCHEDULE_TO_START_TIMEOUT: ${APP_TEMPORAL_CONNECTION_ACTIVITY_SCHEDULE_TO_START_TIMEOUT}
      APP_TEMPORAL_CONNECTION_ACTIVITY_SCHEDULE_TO_CLOSE_TIMEOUT: ${APP_TEMPORAL_CONNECTION_ACTIVITY_SCHEDULE_TO_CLOSE_TIMEOUT}
      APP_TEMPORAL_CONNECTION_ACTIVITY_HEARTBEAT_TIMEOUT: ${APP_TEMPORAL_CONNECTION_ACTIVITY_HEARTBEAT_TIMEOUT}
      APP_TEMPORAL_CONNECTION_ACTIVITY_RETRY_OPTIONS_INITIAL_INTERVAL: ${APP_TEMPORAL_CONNECTION_ACTIVITY_RETRY_OPTIONS_INITIAL_INTERVAL}
      APP_TEMPORAL_CONNECTION_ACTIVITY_RETRY_OPTIONS_MAXIMUM_INTERVAL: ${APP_TEMPORAL_CONNECTION_ACTIVITY_RETRY_OPTIONS_MAXIMUM_INTERVAL}
      APP_TEMPORAL_CONNECTION_ACTIVITY_RETRY_OPTIONS_BACKOFF_COEFFICIENT: ${APP_TEMPORAL_CONNECTION_ACTIVITY_RETRY_OPTIONS_BACKOFF_COEFFICIENT}
      APP_TEMPORAL_CONNECTION_ACTIVITY_RETRY_OPTIONS_MAXIMUM_ATTEMPTS: ${APP_TEMPORAL_CONNECTION_ACTIVITY_RETRY_OPTIONS_MAXIMUM_ATTEMPTS}
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "8080:8080"
